Description: Akins/Udacity Network
Parameters:
  EnvironmentName:
    Type: String
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
Resources:
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref DevVPC

# Outputs:
#   DevVPCID:
#     Value: !Ref DevVPC
#     Export:
#       Name: !Sub "${EnvironmentName}-VPCID"

  